config/routes.rb
Distlist::Application.routes.draw do
  devise_for :users, :path_prefix => '/:locale/auth'

  scope "/:locale", :locale => /en|it|fr/ do
    resources :campaigns do
      resources :addresses do
        get :import, :on => :collection
        post :csv, :on => :collection
        get :export, :on => :collection
      end
      resources :emails do
        resources :attachments, :only => [:show, :create, :destroy]
        put :getlog, :on => :member
        put :mail_me, :on => :member
      end
    end
  
    resources :users, :only => [:index, :create, :destroy, :new, :show] do
      put :endis, :on => :member
      put :swadmin, :on => :member 
    end

    get "/home" => "home#index" 
    get "/helpdesk" => "home#helpdesk", :as => :helpdesk
    get "/admin" => "home#admin", :as => :admin
    get "/attachment/:id/:file_file_name" => "attachments#public", :as => :apublic
    get "/unsubscribe/:campaign_id/:pepper" => "addresses#unsubscribe", :as => :unsubscribe
    post "/unsubscribe/:campaign_id/:pepper/:id" => "addresses#unsubscribe_confirm", :as => :unsubscribe_confirm
  end

  get "/:locale" => "home#index"

  root :to => 'home#index', :locale => :en

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :campaigns, :dependent => :destroy

  default_scope order('email')
  
  def to_admin!
    toggle!(:admin) unless admin == true
  end

  def no_admin!
    toggle!(:admin) if admin == true
  end

  def div
    return "user_" + to_param
  end

  def emails_counter
    return Email.where(:campaign_id => campaigns.map{|c| c.id}).count
  end

  def addresses_counter
    return Address.where(:campaign_id => campaigns.map{|c| c.id}).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_required!
  before_filter :prerequisite, only: [:index, :new, :create] 

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, notice: "success"
    else
      render :new
      #redirect_to new_user_path, notice: "Fail: " + @user.errors.messages.inject([]){|nemo,(k,v)| nemo << [k,": ",v].join; nemo}.join(", ")
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: "success"
  end

  def endis
    @user = User.find(params[:id])
    @user.access_locked? ? @user.unlock_access! : @user.lock_access!
    redirect_to users_path, notice: "success"
  end

  def swadmin
    @user = User.find(params[:id])
    @user.admin? ? @user.no_admin! : @user.to_admin!
    redirect_to users_path, notice: "success"
  end
  
  private
  
  def prerequisite
    @user_count = User.all.count
    @campaign_count = Campaign.all.count
    @email_count = Email.all.count
    @address_count = Address.all.count
    @sended_count = Log.sum(:row_count)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f| 
  %fieldset
    %legend= t("site.users.new_user") 

    .form-inputs
      .separator= f.input :email

      .separator= f.input :password

      .separator= f.input :password_confirmation

    %div{class: "form-actions"}
      .separator= f.button :submit

app/views/users/_user.html.haml
%li{class: [cycle('bdark','bnormal'), ('disable' if user.access_locked?)]}
  = user.admin? ? image_tag('16/user-admin.png') : image_tag('16/user-normal.png')
  = user.email
  %span.fright.little
    = link_to t("site.users.swadmin"), swadmin_user_path(user), method: :put
    |
    = link_to t("site.users.endis"), endis_user_path(user), method: :put
    |
    = link_to t("site.common.destroy"), user_path(user), method: :delete
  .little
    = t("users.last")
    = ": "
    = user.last_sign_in_at.blank? ? "never" : l(user.last_sign_in_at)
    = ", "
    = t("users.campaigns")
    = ": "
    = user.campaigns.all.count

app/views/users/_user_info.html.haml
.description
  %h3= t("users.info")
  %dl
    .clear
      %dt= t("site.common.users")
      %dd= @user_count
    .clear
      %dt= t("site.common.campaigns")
      %dd= @campaign_count
    .clear
      %dt= t("site.common.emails")
      %dd= @email_count
    .clear
      %dt= t("site.common.addresses")
      %dd= @address_count
    .clear
      %dt= t("site.emails.log_entry")
      %dd= @sended_count

app/views/users/index.html.haml
%article{id: 'users'}
  %h1.tcenter= t("site.users.title")
  = render "user_info"
  #more_content
    %h2.tcenter= t('site.users.title_list')
    %ul.list= render @users
    .tcenter.p10
      =link_to t('site.common.new'), new_user_path

app/views/users/new.html.haml
%h1= t("site.users.title")
= render "user_info"
#more-contents
  %h2.tcenter= t('site.users.title_list')
  = render 'form'
  .tcenter.p10
    = link_to t('site.common.back'), users_path