config/routes.rb
Distlist::Application.routes.draw do
  devise_for :users, :path_prefix => '/:locale/auth'

  scope "/:locale", :locale => /en|it|fr/ do
    resources :campaigns do
      resources :addresses do
        get :import, :on => :collection
        post :csv, :on => :collection
        get :export, :on => :collection
      end
      resources :emails do
        resources :attachments, :only => [:show, :create, :destroy]
        put :getlog, :on => :member
        put :mail_me, :on => :member
      end
    end
  
    resources :users, :only => [:index, :create, :destroy, :new, :show] do
      put :endis, :on => :member
      put :swadmin, :on => :member 
    end

    get "/home" => "home#index" 
    get "/helpdesk" => "home#helpdesk", :as => :helpdesk
    get "/admin" => "home#admin", :as => :admin
    get "/attachment/:id/:file_file_name" => "attachments#public", :as => :apublic
    get "/unsubscribe/:campaign_id/:pepper" => "addresses#unsubscribe", :as => :unsubscribe
    post "/unsubscribe/:campaign_id/:pepper/:id" => "addresses#unsubscribe_confirm", :as => :unsubscribe_confirm
  end

  get "/:locale" => "home#index"

  root :to => 'home#index', :locale => :en

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  require 'csv'
  before_filter :authenticate_user!, except: [:unsubscribe, :unsubscribe_confirm]
  before_filter :prerequisite, except: [:unsubscribe, :unsubscribe_confirm]

  def index
    @addresses = @campaign.addresses.page(params[:page])
  end

  def new
    @address = @campaign.addresses.new
    5.times {@address.options.build}
  end

  def edit
    @address = @campaign.addresses.find(params[:id])
    5.times { |t| @address.options.build }
  end

  def create
    @address = @campaign.addresses.new(params[:address])

    if @address.save
      redirect_to campaign_addresses_path(@campaign), notice: "Success"
    else
      render action: "new" 
    end
  end

  def update
    @address = @campaign.addresses.find(params[:id])

    if @address.update_attributes(params[:address])
      redirect_to campaign_addresses_path(@campaign), notice: "Success"
    else
      render "edit"
    end
  end

  def import
  end

  def export
    key =  Hash[Option.where(address_id: @campaign.addresses.all.map{|a| a.id}).group(:key).select(:key).map{|o| [o.key,nil]}]
    @csv = CSV.generate do |csv|
      csv << ["email","name","surname"] + key.keys
      @campaign.addresses.each do |address|
        csv << [address.email, address.name, address.surname] + key.merge(Hash[address.options.map{|o| [o.key, o.value]}]).values
      end
    end
    send_data(@csv, :type => 'text/csv; charset=utf-8; header=present', :filename => 'export.csv')  
  end

  def csv
    unless params[:file].blank?
      report = save_csv(params[:file])
      redirect_to campaign_addresses_path(@campaign), notice: "Imported. Error: #{report[:error_counter]} (#{report[:error_row].join(',')})"
    else
      render "import", notice: "Select a file csv"
    end
  end

  def destroy
    @address = @campaign.addresses.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.js
      format.html {redirect_to campaign_addresses_path(@campaign), notice: "Success"}
    end
  end

  def unsubscribe
    @campaign = Campaign.where(:unsubscribe => true).find(params[:campaign_id])
    @address = @campaign.addresses.find_by_pepper(params[:pepper])
    record_not_found if @address.blank?
  end

  def unsubscribe_confirm
    @campaign = Campaign.where(:unsubscribe => true).find(params[:campaign_id])
    @address = @campaign.addresses.find(params[:id])
    @address.delete if @address.pepper == params[:pepper]
  end

  private

  def prerequisite
    @campaign = current_user.campaigns.find(params[:campaign_id])
  end

  def save_csv(file)
    csv = CSV.parse(file.read, :headers => true)
    counter = 1
    error_counter = 0
    error_row = Array.new
    csv.each do |row|
      row = row.to_hash.with_indifferent_access
      address = @campaign.addresses.new(email: row['email'], name: row['name'], surname: row['surname'])
      row.each { |k,v| address.options.build( key: String.new(k).parameterize, value: v ) if !k.blank? && !v.blank? && !['email','name','surname'].include?(String.new(k)) }
      # address = @campaign.addresses.new(email: row['email'], name: row['name'], surname: row['surname'])
      if address.save
        counter = counter.next
      else
        error_counter = error_counter.next
        error_row << counter
        counter = counter.next
      end
    end
    return {error_counter: error_counter, error_row: error_row}
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.haml
%li{id: address.div, class: [cycle('bdark',nil),'list']}
  .fright= link_to image_tag('16/destroy.png'), campaign_address_path(@campaign, address), method: :delete, confirm: I18n.t('site.common.are_sure')
  = link_to image_tag("16/people.png") + " " + address.recipient, edit_campaign_address_path(@campaign, address)
  - unless address.tag_list.blank?
    %span.tag= " | " + address.tag_list
  .little
    - address.options.each do |option|
      = option.tkey
      = " => "
      = option.value
      %span.red= " - "

app/views/addresses/_form.html.haml
%section{id: @address.div}
  
  = simple_form_for([@campaign, @address]) do |f|
    %fieldset
      %legend= @address.new_record? ? t("addresses.new_address") : @address.recipient
      = f.error_notification

      .form-inputs
        .separator= f.input :email
        .separator= f.input :name
        .separator= f.input :surname
        .separator= f.input :tag_list

        %br
      
        = f.simple_fields_for :options do |o|
          %div{class: ['inline', 'separator'] }
            = o.input :key, input_html: {size: 10}
            = o.input :value, input_html: {size: 10}
            = o.input :_destroy, :as => :select, :include_blank => false, :default => false

        %br
      .form-actions
        = f.button :submit

app/views/addresses/_import.html.haml
%section#import
  = form_tag("/campaigns/#{@campaign.to_param}/addresses/csv", multipart: true) do
    %fieldset
      %legend= t("users.import")
      .clear
        = label_tag :file, "csv file"
        = file_field_tag :file
        = submit_tag("import now")

app/views/addresses/destroy.js.haml
$("article##{@address.div}").remove();

app/views/addresses/edit.html.haml
%article{id: @campaign.div}
  = render :partial => "campaign_details"
  #more_content
    %section{id: 'addresses'}
      %h2.tcenter= t("addresses.title")
      = render 'form'
      .tcenter
        = link_to( t("site.common.back").html_safe + image_tag('16/back.png'), campaign_addresses_path(@campaign))
        = " | "
        = link_to( t("site.common.import").html_safe + image_tag('16/import.png'), import_campaign_addresses_path(@campaign))
        = " | "
        = link_to( t("site.common.export").html_safe + image_tag('16/export.png'), export_campaign_addresses_path(@campaign))

app/views/addresses/import.html.haml
%article{id: @campaign.div}
  = render :partial => "campaign_details"
  #more_content
    %section{id: 'addresses'}
      %h2.tcenter= t("addresses.title")
      = render 'import'
      .tcenter
        = link_to( t("site.common.back").html_safe + image_tag("16/back.png"), campaign_addresses_path(@campaign))
        = " | "
        = link_to( t("site.common.import").html_safe + image_tag('16/import.png'), import_campaign_addresses_path(@campaign))
        = " | "
        = link_to( t("site.common.export").html_safe + image_tag('16/export'), export_campaign_addresses_path(@campaign))

app/views/addresses/index.html.haml
%article{id: @campaign.div}
  = render :partial => "campaign_details"
  #more_content
    %section{id: 'addresses'}
      %h2.tcenter= t("site.addresses.title")
      %ul.list= render @addresses
      .command
        = paginate @addresses
        = link_to t('site.common.new').html_safe + image_tag('16/new.png'), new_campaign_address_path(@campaign)
        = " | "
        = link_to t('site.common.import').html_safe + image_tag('16/import.png'), import_campaign_addresses_path(@campaign)
        = " | "
        = link_to t('site.common.export').html_safe + image_tag('16/export.png'), export_campaign_addresses_path(@campaign)

app/views/addresses/new.html.haml
%article{id: @campaign.div}
  = render :partial => "campaign_details"
  #more_content
    %section{id: 'addresses'}
      %h2.tcenter= t("addresses.title")
      = render 'form'
      .tcenter.clear
        = link_to( t("site.common.back").html_safe + image_tag('16/back.png'), campaign_addresses_path(@campaign))
        = " | "
        = link_to( t("site.common.import").html_safe + image_tag('16/import.png'), import_campaign_addresses_path(@campaign))
        = " | "
        = link_to( t("site.common.export").html_safe + image_tag('16/export.png'), export_campaign_addresses_path(@campaign))

app/views/addresses/unsubscribe.html.haml
%article{id: "distlist"}  %h1.tcenter= t('devise.sessions.title')  .description.slide    = image_tag('bg/Slide.jpg')    .t4.tcenter      %span.blu= t('devise.sessions.description1').html_safe      %span.little= t('devise.sessions.description2').html_safe      %span.red= t('devise.sessions.description3').html_safe    .clear  #more_content    %h2.tcenter= t('site.addresses.title_unsubscribe')    %section#import      = form_tag(unsubscribe_confirm_path(@campaign, @address.pepper, @address)) do        %fieldset          %legend= t("site.addresses.unsubscribe")          .clear            = hidden_field_tag :id, value: 1, as: :hidden            = submit_tag(I18n.t('site.addresses.unsubscribe_action'))

app/views/addresses/unsubscribe_confirm.html.haml
%article{id: "distlist"}  %h1.tcenter= t('devise.sessions.title')  .description.slide    = image_tag('bg/Slide.jpg')    .t4.tcenter      %span.blu= t('devise.sessions.description1').html_safe      %span.little= t('devise.sessions.description2').html_safe      %span.red= t('devise.sessions.description3').html_safe    .clear  #more_content    %h2.tcenter= t('site.addresses.title_unsubscribe')    .description      %h3= t('site.addresses.title_unsubscribed')      %p.tcenter.bold= t('site.addresses.byebye')      