config/routes.rb
Distlist::Application.routes.draw do
  devise_for :users, :path_prefix => '/:locale/auth'

  scope "/:locale", :locale => /en|it|fr/ do
    resources :campaigns do
      resources :addresses do
        get :import, :on => :collection
        post :csv, :on => :collection
        get :export, :on => :collection
      end
      resources :emails do
        resources :attachments, :only => [:show, :create, :destroy]
        put :getlog, :on => :member
        put :mail_me, :on => :member
      end
    end
  
    resources :users, :only => [:index, :create, :destroy, :new, :show] do
      put :endis, :on => :member
      put :swadmin, :on => :member 
    end

    get "/home" => "home#index" 
    get "/helpdesk" => "home#helpdesk", :as => :helpdesk
    get "/admin" => "home#admin", :as => :admin
    get "/attachment/:id/:file_file_name" => "attachments#public", :as => :apublic
    get "/unsubscribe/:campaign_id/:pepper" => "addresses#unsubscribe", :as => :unsubscribe
    post "/unsubscribe/:campaign_id/:pepper/:id" => "addresses#unsubscribe_confirm", :as => :unsubscribe_confirm
  end

  get "/:locale" => "home#index"

  root :to => 'home#index', :locale => :en

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user
  has_many :addresses, :dependent => :destroy
  has_many :emails, :dependent => :destroy
  attr_accessible :footer, :header, :sender_email, :sender_name, :time_gap, :title, :unsubscribe

  validates :user_id, :presence => true
  validates :sender_email, :presence => true
  validates :time_gap, :presence => true, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  validates :title, :presence => true, :uniqueness => { :scope => :user_id}

  def sender
    return "#{self.sender_name} <#{self.sender_email}>"
  end

  def div
    return "campaign_" + self.to_param
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!

  # GET /campaigns
  def index
    @campaigns = current_user.campaigns.page(params[:page])
    @address_count = Address.where(campaign_id: @campaigns.map{|c| c.id}).count
    @email_count = Email.where(campaign_id: @campaigns.map{|c| c.id}).count
  end

  # GET /campaigns/1
  def show
    @campaign = current_user.campaigns.find(params[:id])
  end

  # GET /campaigns/new
  def new
    @campaign = current_user.campaigns.new
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = current_user.campaigns.find(params[:id])
  end

  # POST /campaigns
  def create
    @campaign = current_user.campaigns.new(params[:campaign])

    if @campaign.save
      redirect_to @campaign, notice: 'Campaign was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /campaigns/1
  def update
    @campaign = current_user.campaigns.find(params[:id])

    if @campaign.update_attributes(params[:campaign])
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /campaigns/1
  def destroy
    @campaign = current_user.campaigns.find(params[:id])
    if @campaign.destroy
      @campaigns = current_user.campaigns.all
      render action: "index"
    else
      render action: "show"
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign.html.haml
%section{:id => campaign.div, class: cycle('bdark',nil) }
  = link_to(campaign.title, campaign)
  %span{class: "fright"}= link_to( image_tag("16/edit.png"), campaign )
  .details.little
    %dl{:class => 'linear'}
      %dt= image_tag( "16/next.png" )
      %dd= campaign.emails.sended.count

      %dt= image_tag( "16/mail-new.png" )
      %dd= campaign.emails.not_sended.count

      %dt= image_tag( "16/people.png" )
      %dd= campaign.addresses.count
  .clear

app/views/campaigns/_form.html.haml
%h2.tcenter= @campaign.new_record? ? t('site.common.campaign') : @campaign.title

= simple_form_for(@campaign) do |f| 
  %fieldset
    %legend= @campaign.new_record? ? t("site.campaigns.new_campaign") : t("site.campaigns.edit_campaign")
    = f.error_notification

    .form-inputs
      .separator= f.input :title

      .separator= f.input :sender_name

      .separator= f.input :sender_email

      .separator= f.input :header, :cols => 57, :rows => 4, :input_html => {:class => "elrte"}

      .separator= f.input :footer, :cols => 57, :rows => 4, :input_html => {:class => "elrte"}

      .separator= f.input :time_gap

      .separator= f.input :unsubscribe, :as => :select, :include_blank => false

    %div{class: "form-actions"}
      .separator= f.button :submit

app/views/campaigns/_statistics.html.haml
%h2= t("site.campaigns.statistics")
.description
  %h3= t("site.campaigns.statistics")
  %dl
    .clear
      %dt= link_to t("site.common.emails"), campaign_emails_path(@campaign)
      %dd= @campaign.emails.count
    .clear
      %dt= link_to t("site.common.addresses"), campaign_addresses_path(@campaign)
      %dd= @campaign.addresses.count

app/views/campaigns/edit.html.haml
%article{id: "campaigns"}
  = render 'campaign_details'
  #more_content
    = render partial: 'form'
    .command= link_to(t('site.common.back').html_safe + image_tag('16/back.png'), campaigns_path)

app/views/campaigns/index.html.haml
%article#campaigns
  %h1.tcenter=t("site.campaigns.title")
  .description
    %h3= t('site.common.details')
    %dl
      .clear
        %dt Username
        %dd= current_user.email
      .clear
        %dt= t('site.common.campaigns')
        %dd= @campaigns.count
      .clear
        %dt= t('site.common.emails')
        %dd= @email_count
      .clear
        %dt= t('site.common.addresses')
        %dd= @address_count
        
  #more_content
    %h2= t('site.campaigns.title')
    = render @campaigns
    .command
      = paginate @campaigns
      = link_to t('site.common.new').html_safe + image_tag('16/new.png'), new_campaign_path

app/views/campaigns/new.html.haml
%article{id: "campaigns"}
  = render 'campaign_details'
  #more_content
    = render partial: 'form'
    .command= link_to(t('site.common.back'), campaigns_path)

app/views/campaigns/show.html.haml
%article{id: @campaign.div}
  = render :partial => "campaign_details"
  #more_content
    = render :partial => "statistics"
    .command
      = link_to(t('site.common.emails').html_safe + image_tag('16/mail.png'), campaign_emails_path(@campaign))
      = " | "
      = link_to(t('site.common.addresses').html_safe + image_tag('16/people.png'), campaign_addresses_path(@campaign))