config/routes.rb
Distlist::Application.routes.draw do
  devise_for :users, :path_prefix => '/:locale/auth'

  scope "/:locale", :locale => /en|it|fr/ do
    resources :campaigns do
      resources :addresses do
        get :import, :on => :collection
        post :csv, :on => :collection
        get :export, :on => :collection
      end
      resources :emails do
        resources :attachments, :only => [:show, :create, :destroy]
        put :getlog, :on => :member
        put :mail_me, :on => :member
      end
    end
  
    resources :users, :only => [:index, :create, :destroy, :new, :show] do
      put :endis, :on => :member
      put :swadmin, :on => :member 
    end

    get "/home" => "home#index" 
    get "/helpdesk" => "home#helpdesk", :as => :helpdesk
    get "/admin" => "home#admin", :as => :admin
    get "/attachment/:id/:file_file_name" => "attachments#public", :as => :apublic
    get "/unsubscribe/:campaign_id/:pepper" => "addresses#unsubscribe", :as => :unsubscribe
    post "/unsubscribe/:campaign_id/:pepper/:id" => "addresses#unsubscribe_confirm", :as => :unsubscribe_confirm
  end

  get "/:locale" => "home#index"

  root :to => 'home#index', :locale => :en

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from ActiveRecord::RecordNotFound, :with => :access_denied!
  before_filter :set_locale
 
  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale 
  end

  def default_url_options(options={})
    {:locale => I18n.locale}
  end

  def record_not_found
    redirect_to(root_path, :notice => "Pagina non trovata", :status => 404)
  end

  def access_denied!
    redirect_to(root_path, :notice => "accesso non consentito", :status => 401)
  end

  def admin_required!
    access_denied! unless current_user.try(:admin?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_campaign_details.html.haml
%h1.tcenter= @campaign.new_record? ? t("site.common.campaign") : @campaign.title

.description
  %h3= t("campaigns.campaign_details")
  %dl
    .clear
      %dt= t("site.campaigns.sender")
      %dd
        %div= @campaign.sender
   
    .clear
      %dt= t("site.campaigns.header")
      %dd
        %div= !@campaign.header.blank? ? @campaign.header.html_safe : " - "

    .clear
      %dt= t("site.campaigns.footer")
      %dd
        %div= !@campaign.footer.blank? ? @campaign.footer.html_safe : " - "

    .clear
      %dt= t("site.campaigns.time_gap")
      %dd
        %div= @campaign.time_gap

    .clear
      %dt= t('site.campaigns.email_count')
      %dd
        %div= @campaign.emails.count

    .clear
      %dt= t('site.common.addresses')
      %dd
        %div= @campaign.addresses.count

  .bottom.tcenter
    - unless @campaign.new_record?
      = link_to t("site.common.edit").html_safe + image_tag("16/edit.png"), edit_campaign_path(@campaign)
      = " | "
      = link_to t("site.common.destroy").html_safe + image_tag('16/destroy.png'), campaign_path(@campaign), method: :delete, confirm: "You are sure?"

app/views/application/_nav1.html.haml
%nav
  %ul
    - if user_signed_in?
      %li.user
        = t("menu.welcome")
        = current_user.email
    %li
      = link_to t("menu.home"), root_path
    - if defined?(@campaign) and !@campaign.new_record?
      %li
        = link_to t("menu.campaign"), campaign_path(@campaign)
        %ul
          %li= link_to t("menu.emails"), campaign_emails_path(@campaign)
          %li= link_to t("menu.addresses"), campaign_addresses_path(@campaign)
    %li= link_to t("menu.help"), :helpdesk
    - if current_user.try(:admin?)
      %li= link_to t("menu.admin"), admin_path
    - if user_signed_in?
      %li= link_to image_tag('24/logout.png'), destroy_user_session_path, method: :delete